---
# handlers file for hades
- name: Restart hades scheduler
  become: true
  ansible.builtin.shell: docker-compose -f /opt/hades/scheduler/docker-compose.yml down && docker-compose -f /opt/hades/scheduler/docker-compose.yml up -d
  args:
    chdir: /opt/hades/scheduler
  when: hades_node_role == "scheduler"

- name: Restart hades api
  become: true
  ansible.builtin.shell: docker-compose -f /opt/hades/api/docker-compose.yml down && docker-compose -f /opt/hades/api/docker-compose.yml up -d
  args:
    chdir: /opt/hades/api
  when: hades_node_role == "api"

- name: Reload nginx
  become: true
  ansible.builtin.shell: systemctl reload nginx