# docker compose file for the project with three services

version: '3.7'
services:
  hadesAPI:
    image: ghcr.io/mtze/hades/hades-api
    build:
      context: .
      dockerfile: ./HadesAPI/Dockerfile
    ports:
      # Set the Port to 8081 to avoid conflicts with the artemis server
      - "8081:8080"
    networks:
      - hades
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=rabbitmq:5672
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  hadesScheduler:
    image: ghcr.io/mtze/hades/hades-scheduler
    build:
      context: .
      dockerfile: ./HadesScheduler/Dockerfile
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - hades
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=rabbitmq:5672
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - HADES_EXECUTOR=docker

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - hades
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
networks:
  hades:
