# docker compose file for the project with three services

version: '3.7'
services:
  hadesAPI:
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PWD
      - DEBUG=true
  hadesScheduler:
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PWD
      - HADES_EXECUTOR=docker
      - DOCKER_CONTAINER_AUTOREMOVE=false
      - DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock