--- 

- name: Create hades scheduler directory
  become: true
  ansible.builtin.file:
    path: /opt/hades/scheduler
    state: directory

- name: Create hades config env file
  become: true
  ansible.builtin.template:
    src: hades.env.j2
    dest: /opt/hades/scheduler/.env
    mode: 0644

- name: Add hades scheduler docker compose
  become: true
  ansible.builtin.template:
    src: docker-compose-scheduler.yml.j2
    dest: /opt/hades/scheduler/docker-compose.yml
    mode: 0644

- name: Pull new scheduler docker image
  ansible.builtin.command: docker-compose -f /opt/hades/scheduler/docker-compose.yml pull
  args:
    chdir: /opt/hades/scheduler
  notify: Restart hades scheduler