name: Upload Go test results

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ './HadesAPI', './HadesScheduler', './HadesCloneContainer' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install dependencies
        run: cd ${{ matrix.directory }} && go mod download
      - name: Test with Go
        run: go test ./${{ matrix.directory }}/... -json > TestResults-${{ matrix.directory }}.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.directory }}
          path: TestResults-${{ matrix.directory }}.json
